---
- name: Install yarn with npm
  community.general.npm:
    name: yarn
    global: true
    state: present

- name: Install pm2 with npm
  community.general.npm:
    name: "pm2"
    global: true
    state: present

