---
- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  pre_tasks:
    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install LEMP Packages
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [
        'nginx',
        'git',
        'gpg',
        'curl',
        'wget',
        'tar',
        'ufw',
        'python3-pymysql',
        'python3-pexpect',
      ]

    # Node.js Installation
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

  tasks:

    # Cli Installations

    - include_tasks: tasks/cli.yml

    # Nginx Configuration

    - include_tasks: tasks/nginx.yml

    # Nuxt App Installation

    - include_tasks: tasks/application.yml

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Delete Directory Ansible
      ansible.builtin.file:
        state: absent
        path: /var/www/vertigo-nuxt/ansible

  handlers:

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
